### ISSUE TITLE
plugin/mapping.vim should be renamed.

### ISSUE THREAD

**Issue by wsdjeg** [lymslive/vnote#2]
dein merge plugins by default,  plugin/mapping.vim maybe overrided by other plugins.

I think the script file name should plugin/vnote.vim only, and the mapping should be move to autoload/vnote/*.

**Comment by lymslive** [comment]
at the very beginning, I put the <Plug> remap in autoload/.
later some time, I consider a case in witch user press a key map before the scripte in autoload/ having a changing to load. so move to plugin/.
If this is problem, move back to autoload is also ok.
