### ISSUE TITLE
Unknown command DLOG

### ISSUE THREAD

**Issue by wsdjeg** [lymslive/vnote#4]
when using this plugin, I got `Not an editor command: :DLOG 'class#notebook is loading ...'`

https://github.com/lymslive/vnote/blob/master/autoload/class/notebook.vim#L347

**Comment by lymslive** [comment]
This plugin may not fit for you or your SpaceVim, as it dependent on my another more basic plugin vimloo.
But you may fix it by defining an empty command for `:DLOG`, seams it only for debug purpose.
Please refer to:
https://github.com/lymslive/vimloo/blob/dev/autoload/vimloo/plugin.vim

**Comment by wsdjeg** [comment]
Thanks, I got it.
--------------
wsdjeg
